// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vente.Data;

#nullable disable

namespace Vente.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20231218005904_two")]
    partial class two
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vente.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Vente.Models.Proprietaire", b =>
                {
                    b.Property<int?>("IDUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("AdresseEntreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUtilisateur");

                    b.ToTable("Proprietaires");
                });

            modelBuilder.Entity("Vente.Models.Utilisateurs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Vente.Models.Admin", b =>
                {
                    b.HasOne("Vente.Models.Utilisateurs", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("ID");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Vente.Models.Proprietaire", b =>
                {
                    b.HasOne("Vente.Models.Utilisateurs", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IDUtilisateur");

                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
