// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vente.Data;

#nullable disable

namespace Vente.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vente.Models.Admin", b =>
                {
                    b.Property<int>("ID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Vente.Models.Categorie", b =>
                {
                    b.Property<int>("CategorieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategorieID"));

                    b.Property<string>("CategorieName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategorieID");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("Vente.Models.Produit", b =>
                {
                    b.Property<int>("IdPr")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPr"));

                    b.Property<DateTime>("DateExpiration")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IDC")
                        .HasColumnType("int");

                    b.Property<int>("IDP")
                        .HasColumnType("int");

                    b.Property<byte[]>("ImageData")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("prix")
                        .HasColumnType("float");

                    b.HasKey("IdPr");

                    b.HasIndex("IDC");

                    b.HasIndex("IDP");

                    b.ToTable("Produits");
                });

            modelBuilder.Entity("Vente.Models.Proprietaire", b =>
                {
                    b.Property<int?>("IDUtilisateur")
                        .HasColumnType("int");

                    b.Property<string>("AdresseEntreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomEntreprise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IDUtilisateur");

                    b.ToTable("Proprietaires");
                });

            modelBuilder.Entity("Vente.Models.Utilisateurs", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("Vente.Models.Admin", b =>
                {
                    b.HasOne("Vente.Models.Utilisateurs", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("ID");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Vente.Models.Produit", b =>
                {
                    b.HasOne("Vente.Models.Categorie", "Categories")
                        .WithMany()
                        .HasForeignKey("IDC");

                    b.HasOne("Vente.Models.Proprietaire", "proprietaires")
                        .WithMany()
                        .HasForeignKey("IDP");

                    b.Navigation("Categories");

                    b.Navigation("proprietaires");
                });

            modelBuilder.Entity("Vente.Models.Proprietaire", b =>
                {
                    b.HasOne("Vente.Models.Utilisateurs", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("IDUtilisateur");

                    b.Navigation("Utilisateur");
                });
#pragma warning restore 612, 618
        }
    }
}
